### ISSUE TITLE
ValueError : too many values to unpack

### ISSUE THREAD

**Issue by NotTested** [36base/girlsfrontline-resources-extract#14]
resource_avgtexture8.ab 파일 까려고 시도했을때 발생하네요. 
호출스택은 다음과 같습니다.

```
PS D:\sd\2_2_2_> .\girlsfrontline-resources-extract.exe ..\New\resource_avgtexture8.ab
INFO | girlsfrontline-resources-extractor: 2.2.2
INFO | Start Extracting: 2019-10-30 04:24:26
INFO |
=== AssetBundle File: resource_avgtexture8.ab ===
INFO | assets/resources/dabao/avgtexture/cg.5.png
Traceback (most recent call last):
  File "main.py", line 82, in <module>
  File "main.py", line 63, in main
  File "abunpack.py", line 450, in abunpack
  File "abunpack.py", line 356, in save_processed_resources
  File "abunpack.py", line 269, in get_resource
ValueError: too many values to unpack (expected 2)
[25000] Failed to execute script main
```

**Comment by Erincian** [comment]
resource_avgtexture8.ab 이외에도
resource_avgtexture10.ab
resource_avgtexture11.ab
을 깔 때도 같은 현상이 발생하며 일부 파일이 누락됩니다
