### ISSUE TITLE
폰트 데이터 추출 불가능

### ISSUE THREAD

**Issue by Lastorder-DC** [36base/girlsfrontline-resources-extract#4]
```
INFO | Start Extracting : 2018-08-07 10:01:16
INFO | === AssetBundle File: asset_fonts.ab ===
Traceback (most recent call last):
  File "main.py", line 68, in <module>
  File "main.py", line 49, in main
  File "abunpack.py", line 446, in abunpack
  File "abunpack.py", line 315, in save_original_resources
  File "abunpack.py", line 267, in get_resource
  File "abunpack.py", line 113, in __init__
AttributeError: 'NoneType' object has no attribute 'shape'
[3232] Failed to execute script main
```

**Comment by krepe-suZette** [comment]
![image](https://user-images.githubusercontent.com/37508580/43755099-500be776-9a49-11e8-91b6-642f9fa32fb8.png)

문제되는 파일을 찾아봤는데... 포맷 종류는 `Texture2D`고, 데이터는하나도 없고 여러모로 복잡하네요.
저 파일만 봤을때는 추출 가능한 데이터도 없으니, 예외처리 적당히 하면 될 것 같습니다.

![image](https://user-images.githubusercontent.com/37508580/43755839-ed893cc6-9a4c-11e8-9eb8-0f48439beb77.png)

그리고  `Font` 타입의 리소스는 지금 추출이 안되실텐데, 별 문제 없으면 추가해서 업데이트 하도록 하겠습니다.
